import bagel.*;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.Properties;

/**
 * Class representing the enemy car that can have collisions with other game entities and shoot random fireballs
 */
public class EnemyCar extends DamageableGameEntity {
    private final Image IMAGE;
    private int speed_y;
    private final List<Fireball> FIREBALLS;
    private static final int FIREBALL_DIVISIBILITY = 300;
    private static final int RANDOM_BOUND = 1000;
    private final Smoke SMOKE;
    private final Fire FIRE;

    /**
     *
     * @param x x-coordinate of the enemy car
     * @param y y-coordinate of the enemy car
     * @param healthPoints The health points of enemy
     * @param damage The damage points it can impact on other entities
     * @param timeout_move_speed The speed that it should move in the first few frames during the collision timeout
     * @param radius The radius of the enemy
     * @param gameProps The Game Property where stores essential details information
     */
    public EnemyCar(int x, int y, double healthPoints, double damage, int timeout_move_speed,
                    double radius, Properties gameProps) {
        super(x, y, healthPoints, damage, timeout_move_speed, radius, gameProps);
        Random rand = new Random();
        speed_y = rand.nextInt(4) + 2;
        IMAGE = new Image(gameProps.getProperty("gameObjects.enemyCar.image"));
        FIREBALLS = new ArrayList<>();
        SMOKE = new Smoke(x, y, gameProps);
        FIRE = new Fire(x, y, gameProps);
    }

    /**
     * Updates the enemy's health points and other information when it receives damages during a collision
     *
     * @param damage The damage points received by the enemy
     * @param onTop true if the enemy is the entity on top when the collision occurred; otherwise, false
     */
    @Override
    public void takeDamage(double damage, boolean onTop) {
        double prevHealthPoints = this.getHealthPoints();
        updateHealthPoints(damage);
        SMOKE.setFramesActive(SMOKE.getFramesActive() + 1);

        if (this.getHealthPoints() < prevHealthPoints) {
            // there is a collision effect
            this.setCollisionTimeoutFrame(this.getCollisionTimeoutFrames() + 1);
            this.setCollisionOnTop(onTop);
        }
    }

    /**
     * show the enemy's image on its current location
     */
    @Override
    public void draw() {
        IMAGE.draw(this.getX(), this.getY());
    }

    /**
     * updates on its location based on user's input
     *
     * @param input User's current input
     */
    @Override
    public void adjustToInputMovement(Input input) {
        if (input.wasPressed(Keys.UP)) {
            this.setY(this.getY() + this.getScrollSpeedY());
        }
    }

    /**
     * update the enemy based on the user's input and other statuses
     *
     * @param input User's current input
     */
    public void update(Input input) {
        updateCollisionTimeout();
        adjustToInputMovement(input);
        if (!this.isDestroyed()) {
            generateRandomFireballs();
            if (this.getCollisionTimeoutFrames() <= 0) {
                this.setY(this.getY() - speed_y);
            }
            draw();
        } else {
            FIRE.setFramesActive(FIRE.getFramesActive() + 1);
        }
        SMOKE.update(this.getX(), this.getY());
        FIRE.update(this.getX(), this.getY());
    }

    private void generateRandomFireballs() {
        Random random = new Random();
        int randomNum = random.nextInt(RANDOM_BOUND);
        if (randomNum % FIREBALL_DIVISIBILITY == 0) {
            FIREBALLS.add(new Fireball(this.getX(), this.getY(), this.getGameProps()));
        }
    }

    /**
     * Gets the list of fireballs get are generated by the enemy
     *
     * @return its list of fireballs
     */
    public List<Fireball> getFireBalls() {
        return this.FIREBALLS;
    }
}
